remove dependency on linux/wireless.h
kernel headers are broken for use in userspace, because the types
defined by them clash with libc headers.
i made a small wireless_lite.h which contains the important bits
and pieces in a clean way.

fixes build on musl libc.
these were the errors:

gcc -std=gnu99 -O3 -Wall -Wextra -o hcxdumptool hcxdumptool.c -lrt -lpthread
In file included from /usr/include/linux/wireless.h:74:0,
                 from hcxdumptool.c:27:
/usr/include/linux/if.h:142:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^~~~~
In file included from hcxdumptool.c:17:0:
/usr/include/net/if.h:64:8: note: originally defined here
 struct ifmap {
        ^~~~~
In file included from /usr/include/linux/wireless.h:74:0,
                 from hcxdumptool.c:27:
/usr/include/linux/if.h:176:8: error: redefinition of 'struct ifreq'
 struct ifreq {
        ^~~~~
In file included from hcxdumptool.c:17:0:
/usr/include/net/if.h:76:8: note: originally defined here
 struct ifreq {
        ^~~~~
In file included from /usr/include/linux/wireless.h:74:0,
                 from hcxdumptool.c:27:
/usr/include/linux/if.h:225:8: error: redefinition of 'struct ifconf'
 struct ifconf  {
        ^~~~~~
In file included from hcxdumptool.c:17:0:
/usr/include/net/if.h:116:8: note: originally defined here
 struct ifconf {
        ^~~~~~